name: sneakers_app
description: A Sneakers App - Flutter

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  simple_animations: ^3.1.0  # downgraded to version 3.1.0
  supercharged: ^2.1.1
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.7.0
  custom_navigation_bar: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/background.png
    - assets/illustration.png

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
